web:
    restart: always
    image: docker.io/nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
        - /etc/localtime:/etc/localtime:z # Share timezone data with host
    links:
        - graylog

fluentd:
    restart: always
    image: docker.io/eeacms/fluentd
    links:
        - graylog
    ports:
        - "5140:5140/udp"
    volumes_from:
        - data
    volumes:
        - ./fluentd/fluent.conf:/etc/fluent/fluent.conf:z # Configuration
        - /etc/localtime:/etc/localtime:z # Share timezone data with host

graylog:
    restart: always
    image: docker.io/eeacms/graylog2:latest
    hostname: graylog.service
    env_file:
        - .secret.env
        - graylog.env
    ports: 
        - "12201:12201/udp"
        - "1514:1514/tcp"
        - "2812:2812"
    links:
        - "elasticsearch:elasticsearch.service"
        - "mongodb:mongodb.service"
        - "postfix:postfix.service"
    volumes_from:
        - data
    volumes:
        - /etc/localtime:/etc/localtime:z # Share timezone data with host
        - ./monit/conf.d:/etc/monit/conf.d:z


postfix:
    restart: always
    image: eeacms/postfix:eionet
    volumes:
        - /etc/localtime:/etc/localtime:z
    env_file:
        - .postfix.secret

mongodb:
    image: docker.io/mongo:3.0.7
    restart: always
    command: --smallfiles --quiet --logappend --logpath=/logs/mongodb/mongodb.log --dbpath=/data/mongodb
    volumes_from:
        - data

elasticsearch:
    image: docker.io/elasticsearch:1.7.3
    restart: always
    volumes_from:
        - data
    command: -Des.cluster.name=graylog2 -Des.path.data=/data/elasticsearch -Des.path.logs=/logs/elasticsearch/

setup:
    image: docker.io/alpine
    volumes_from:
        - data
    volumes:
        - ./setup/setup.sh:/setup.sh:z
    command: /setup.sh

data:
    image: docker.io/busybox
    volumes:
        - /data
        - /logs
    command: "/bin/true"
