mongo-data:
    image: docker.io/busybox
    volumes:
        - /data
    command: ['chown', '-R', '999:', '/data']

es-data:
    image: docker.io/busybox
    volumes:
        - /data/elasticsearch
    command: ['chown', '-R', '105:100', '/data']

postfix:
    restart: always
    image: eeacms/postfix:eionet
    volumes:
        - /etc/localtime:/etc/localtime:ro
    env_file:
        - .postfix.secret

mongodb:
    image: docker.io/mongo:3.0.10
    restart: always
    command: "--smallfiles --quiet --logappend --logpath=/data/mongodb.log --dbpath=/data/db"
    volumes:
        - /etc/localtime:/etc/localtime:ro
    volumes_from:
        - mongo-data

elasticsearch:
    image: docker.io/elasticsearch:2.3.1
    restart: always
    volumes:
        - /etc/localtime:/etc/localtime:ro
    command: "elasticsearch -Des.cluster.name='graylog2' -Des.path.data=/data/elasticsearch -Des.path.logs=/data"
    env_file:
        - elastic.env
    volumes_from:
        - es-data

graylog-master:
    restart: always
    image: docker.io/eeacms/graylog2:2.0.2
    env_file:
        - .secret.env
        - graylog.env
    environment:
        - ENABLED_SERVICES=web,server
        - GRAYLOG_IS_MASTER=true
    ports:
        - "9000:9000"
        - "12900:12900"
    links:
        - "elasticsearch:elasticsearch"
        - "mongodb:mongodb"
        - "postfix:postfix"
    volumes:
        - /etc/localtime:/etc/localtime:ro

graylog-client-1:
    restart: always
    image: docker.io/eeacms/graylog2:2.0.2
    env_file:
        - .secret.env
        - graylog.env
    environment:
        - GRAYLOG_IS_MASTER=false
        - ENABLED_SERVICES=server
    links:
        - "elasticsearch:elasticsearch"
        - "mongodb:mongodb"
        - "postfix:postfix"
    volumes:
        - /etc/localtime:/etc/localtime:ro

loadbalancer:
    restart: always
    image: docker.io/eeacms/logcentralbalancer
    ports:
        - "1514:1514/tcp"
        - "1514:1514/udp"
        - "12201:12201/udp"
        - "12201:12201/tcp"
    volumes:
        - /etc/localtime:/etc/localtime:ro
    links:
        - "graylog-master"
        - "graylog-client-1"
