data:
    image: docker.io/busybox
    volumes:
        - /data
        - /logs
    command: "/bin/true"

setup:
    image: docker.io/alpine
    volumes_from:
        - data
    volumes:
        - ./setup/setup.sh:/setup.sh:z
    command: /setup.sh

postfix:
    restart: always
    image: eeacms/postfix:eionet
    volumes:
        - /etc/localtime:/etc/localtime:ro
    env_file:
        - .postfix.secret

mongodb:
    image: docker.io/mongo:3.0.10
    restart: always
    command: "--smallfiles --quiet --logappend --logpath=/logs/mongodb/mongodb.log --dbpath=/data/mongodb"
    volumes:
        - /etc/localtime:/etc/localtime:ro
    volumes_from:
        - data

elasticsearch:
    image: docker.io/elasticsearch:2.3.1
    restart: always
    volumes:
        - /etc/localtime:/etc/localtime:ro
    command: "elasticsearch -Des.cluster.name='graylog2' -Des.path.data=/data/elasticsearch -Des.path.logs=/logs/elasticsearch/"
    env_file:
        - elastic.env
    volumes_from:
        - data

graylog:
    restart: always
    #image: docker.io/eeacms/graylog2:1.3.4.1
    image: lucas/graylog2:2.0.2
    #image: graylog2/server:2.0.2-2
    environment:
        - ENABLED_SERVICES=web,server
        - GRAYLOG_IS_MASTER=true
    env_file:
        - .secret.env
        - graylog.env
    ports:
        - "12201:12201/udp"
        - "1514:1514/tcp"
        - "2812:2812"
        - "9000:9000"
        - "12900:12900"
    links:
        - "elasticsearch:elasticsearch"
        - "mongodb:mongodb"
        - "postfix:postfix"
    volumes:
        - /etc/localtime:/etc/localtime:ro

fluentd:
    restart: always
    image: docker.io/eeacms/fluentd
    links:
        - graylog
    ports:
        - "5140:5140/udp"
    volumes:
        - ./config/fluent.conf:/etc/fluent/fluent.conf:z # Configuration
        - /etc/localtime:/etc/localtime:ro
