web:
    build: ./nginx/
    ports:
        - "8000:80"
    links:
        - elasticsearch

elasticsearch:
    build: ./elasticsearch
    volumes:
        - ./data/es:/data

fluentd:
    build: ./fluentd
    links:
        - elasticsearch
    ports:
        - "5140:5140"
        - "5140:5140/udp"
