web:
    build: ./nginx/
    ports:
        - "8000:80"
    links:
        - elasticsearch

gen1:
    build: ./generators/app1/
    command: python app.py
    volumes:
        - ./generators/app1/app/:/code
    links:
        - fluentd

gen2:
    build: ./generators/app2/
    command: python app.py
    volumes:
        - ./generators/app2/app/:/code
    links:
        - fluentd

elasticsearch:
    build: ./elasticsearch
    volumes:
        - ./data/es:/data

fluentd:
    build: ./fluentd
    links:
        - elasticsearch
