web:
    restart: always
    image: docker.io/nginx
    ports:
        - "80:80"
        - "1514:1514/tcp"
        - "2812:2812"
    volumes:
        - ./config/nginx.multinode.conf:/etc/nginx/nginx.conf:z
        - /etc/localtime:/etc/localtime:ro
    links:
        - graylog-web
        - graylog-master
        - graylog-client

fluentd:
    restart: always
    image: docker.io/eeacms/fluentd
    links:
        - web

    ports:
        - "5140:5140/udp"
    volumes_from:
        - data
    volumes:
        - ./config/fluent.multinode.conf:/etc/fluent/fluent.conf:z # Configuration
        - /etc/localtime:/etc/localtime:ro

graylog-master:
    restart: always
    image: docker.io/eeacms/graylog2:1.3.4
    hostname: graylogmaster.service
    env_file:
        - .secret.env
        - graylog.env
    environment:
        - ENABLED_SERVICES=graylog-server
        - GRAYLOG_MASTER=true
        - GRAYLOG_HOSTNAME=graylogmaster
        - GRAYLOG_NODE_ID=master
    ports:
        - "12201:12201/udp"
    links:
        - "elasticsearch:elasticsearch.service"
        - "mongodb:mongodb.service"
        - "postfix:postfix.service"
    volumes_from:
        - data
    volumes:
        - ./config/graylogctl:/opt/graylog2-server/bin/graylogctl:z
        - /etc/localtime:/etc/localtime:ro

graylog-client:
    restart: always
    image: docker.io/eeacms/graylog2:1.3.4
    hostname: graylogclient.service
    env_file:
        - .secret.env
        - graylog.env
    environment:
        - ENABLED_SERVICES=graylog-server
        - GRAYLOG_MASTER=false
        - GRAYLOG_HOSTNAME=graylogclient
        - GRAYLOG_NODE_ID=client
    links:
        - "elasticsearch:elasticsearch.service"
        - "mongodb:mongodb.service"
        - "postfix:postfix.service"
    volumes_from:
        - data
    volumes:
        - ./config/graylogctl:/opt/graylog2-server/bin/graylogctl:z
        - /etc/localtime:/etc/localtime:ro
    ports:
        - "12202:12201/udp"

graylog-web:
    restart: always
    image: docker.io/eeacms/graylog2:1.3.4
    hostname: graylogweb.service
    environment:
        - ENABLED_SERVICES=graylog-web
        - GRAYLOG_SERVER_URIS=http://graylogmaster:12900/,http://graylogclient:12900/
    env_file:
        - .secret.env
        - graylog.env
    links:
        - "elasticsearch:elasticsearch.service"
        - "mongodb:mongodb.service"
        - "postfix:postfix.service"
        - "graylog-master:graylogmaster.service"
        - "graylog-client:graylogclient.service"
    volumes_from:
        - data
    volumes:
        - /etc/localtime:/etc/localtime:ro

postfix:
    restart: always
    image: eeacms/postfix:eionet
    volumes:
        - /etc/localtime:/etc/localtime:ro
    env_file:
        - .postfix.secret

mongodb:
    image: docker.io/mongo:3.0.10
    restart: always
    command: --smallfiles --quiet --logappend --logpath=/logs/mongodb/mongodb.log --dbpath=/data/mongodb
    volumes:
        - /etc/localtime:/etc/localtime:ro
    volumes_from:
        - data

elasticsearch:
    image: docker.io/elasticsearch:1.7.5
    restart: always
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:z
    volumes_from:
        - data
    command: -Des.cluster.name=graylog2 -Des.path.data=/data/elasticsearch -Des.path.logs=/logs/elasticsearch/
    env_file:
        - elastic.env

setup:
    image: docker.io/alpine
    volumes_from:
        - data
    volumes:
        - ./setup/setup.sh:/setup.sh:z
    command: /setup.sh

data:
    image: docker.io/busybox
    volumes:
        - /data
        - /logs
    command: "/bin/true"
