web:
    image: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host
    links:
        - graylog

fluentd:
    build: ./fluentd
    links:
        - graylog
    ports:
        - "5140:5140/udp"
    volumes:
        - ./data/log:/log # Daily rotated file logs by fluentd
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host

graylog:
    image: sjoerdmulder/graylog2
    environment:
        - "GRAYLOG2_PASSWORD=password"
    ports:
        - "12201:12201/udp"
    volumes:
        - ./data/graylog/mongodb:/data/mongodb
        - ./data/graylog/elastic:/data/elasticsearch
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host
