web:
    build: ./nginx/
    ports:
        - "8000:80"
    links:
        - elasticsearch
        - kibana

elasticsearch:
    build: ./elasticsearch
    volumes:
        - ./data/es:/data

fluentd:
    build: ./fluentd
    links:
        - elasticsearch
    ports:
        - "5140:5140"
        - "5140:5140/udp"

kibana:
    image: balsamiq/docker-kibana
    environment:
        KIBANA_SECURE: false
    links:
        - elasticsearch:es
graylog:
    image: sjoerdmulder/graylog2
    ports:
        - "9000:9000"
        - "514:514"
        - "12201:12201"
    environment:
        - "GRAYLOG2_PASSWORD=password"
