web:
    restart: always
    image: docker.io/nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host
    links:
        - graylog

fluentd:
    restart: always
    image: docker.io/eeacms/fluentd
    links:
        - graylog
    ports:
        - "5140:5140/udp"
    volumes_from:
        - data
    volumes:
        - ./fluentd/fluent.conf:/etc/fluent/fluent.conf:ro # Configuration
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host

graylog:
    restart: always
    image: docker.io/eeacms/graylog2:1.2.1
    env_file:
        - .secret.env
        - master.env
    ports: 
        - "12201:12201/udp"
        - "1514:1514/tcp"
    volumes_from:
        - data
    volumes:
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host

data:
    image: docker.io/busybox
    volumes:
        - /data
        - /log
    command: "true"
