web:
    restart: always
    image: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host
    links:
        - graylog

fluentd:
    restart: always
    image: eeacms/fluentd
    links:
        - graylog
    ports:
        - "5140:5140/udp"
    volumes_from:
        - data
    volumes:
        - ./fluentd/fluent.conf:/etc/fluent/fluent.conf:ro # Configuration
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host

graylog:
    restart: always
    image: eeacms/graylog2
    environment:
        # Uncomment this on the first setup to give a one time password for
        # the first configuration.
        # Restart after setting up Admin permissions for the LDAP users
        # and commenting back the GRAYLOG_PASSWORD line
        #- "GRAYLOG_PASSWORD=password"
        - GRAYLOG_NODE_ID=master
    ports:
        - "12201:12201/udp"
    volumes_from:
        - data
    volumes:
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host

data:
    image: busybox
    volumes:
        - /data
        - /log
    command: true
